my:
  greeting: Namaste Bro
  list:
    values: One, Two, Three

db:
  connection: connection-string-here
  host: 127.0.0.1
  port: 5432

management.endpoints.web.exposure.include: "*"
spring.profiles.active: test